//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Intern.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_detail
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public string productName { get; set; }
        public string productImage { get; set; }
        public decimal productPrice { get; set; }
        public decimal quantity { get; set; }
    
        public virtual orders orders { get; set; }
    }
}
