//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Intern.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public int product_id { get; set; }
        public string product_name { get; set; }
        public Nullable<int> product_quantity { get; set; }
        public int category_id { get; set; }
        public System.DateTime date_manufacture { get; set; }
        public System.DateTime date_expriration { get; set; }
        public decimal list_price { get; set; }
        public string product_img { get; set; }
        public string product_description { get; set; }
    
        public virtual categories categories { get; set; }
    }
}
